motion:
  -2 : BRAKE
  -1 : STOP
#  0 : .
  1 : Init pose
  2 : OK
  3 : No
  4 : Hi
#  5 : .
#  6 : .
#  7 : .
#  8 : .
#  9 : .
#  10 : .
#  11 : .
#  12 : .
#  13 : .
#  14 : .
  15 : Sit down
  16 : Stand up
#  17 : .
#  18 : .
#  19 : .
#  20 : .
#  21 : .
#  22 : .
#  23 : .
#  24 : .
#  25 : .
#  26 : .
#  27 : .
#  28 : .
#  29 : .
#  30 : .
#  31 : .
  50 : Test 1
  52 : Test 2
motion_shortcut:
# motion_index : button id 
  -1 : 0
  50 : 1
  52 : 2
