motion:
  -2 : BREAK
  -1 : STOP
#  0 : .
  1 : Walking Init
  2 : OK
  3 : No
#  4 : Hi
#  5 : .
#  6 : .
#  7 : .
#  8 : .
#  9 : .
#  10 : .
#  11 : .
#  12 : .
#  13 : .
#  14 : .
  15 : Sit down
  16 : Stand up
#  17 : .
#  18 : .
#  19 : .
#  20 : .
#  21 : .
#  22 : .
#  23 : .
#  24 : .
#  25 : .
#  26 : .
#  27 : .
#  28 : .
#  29 : .
#  30 : .
#  31 : .
  80 : Init pose
  81 : Get up(Front)
  82 : Get up(Back)
  83 : Right Kick
  84 : Left Kick
  85 : Ceremony
motion_shortcut:
# motion_index : button id (0 ~ 9)
  -1 : 0
  81 : 1
  82 : 2
  83 : 3
  84 : 4
