offset:
  head_pan: 0
  head_tilt: 0
  l_ank_pitch: -0.003490658503988659
  l_ank_roll: 0.008726646259971646
  l_el: 0
  l_hip_pitch: -1.695491630976418e-18
  l_hip_roll: 0.003490658503988659
  l_hip_yaw: 0
  l_knee: -0.01919862177193764
  l_sho_pitch: 0
  l_sho_roll: 0
  r_ank_pitch: -0.02617993877991495
  r_ank_roll: 0
  r_el: 0
  r_hip_pitch: -0.007853981633974483
  r_hip_roll: 0.03054326190990077
  r_hip_yaw: 0
  r_knee: 0
  r_sho_pitch: 0
  r_sho_roll: 0
init_pose_for_offset_tuner:
  head_pan: 0
  head_tilt: 0
  l_ank_pitch: 0
  l_ank_roll: 0
  l_el: 0
  l_hip_pitch: 0
  l_hip_roll: 0
  l_hip_yaw: 0
  l_knee: 0
  l_sho_pitch: 0
  l_sho_roll: 0
  r_ank_pitch: 0
  r_ank_roll: 0
  r_el: 0
  r_hip_pitch: 0
  r_hip_roll: 0
  r_hip_yaw: 0
  r_knee: 0
  r_sho_pitch: 0
  r_sho_roll: 0